#Social-links icons set 1

twitterIcon: "icons/bootstrap/twitter.svg"
facebookIcon: "/icons/contact-details/facebook"
linkedInIcon: "/wp-gen/icons/sprite.svg#linkedin"
gitHubIcon: ""
googleBizIcon: "/wp-gen/icons/sprite.svg#google"



