module:
  hugoVersion:
    extended: true
    min: "0.82" #keep increasing as hugo is upgraded locally
  imports:
    - path: github.com/twbs/icons
      ignoreConfig: true
      mounts:
      - source: icons
        target: assets/icons/bootstrap 
    - path: github.com/FortAwesome/Font-Awesome
      mounts:
      - source: svgs
        target: assets/icons/awesome
    - path: github.com/feathericons/feather
      mounts:
      - source: icons
        target: assets/icons/feather
    - path: github.com/simple-icons/simple-icons
      mounts:
      - source: icons
        target: assets/icons/simple

imaging: #HUGO mage processing config
  quality: 90 # default 75
  bgColor: "#fff" # transparency will be maintained but will fall back to this colour for JPEG.


params:
  #####################
  # c-contact-details #
  #####################
  # contactPhoneURL: "#"
  # contactPhoneText: "DEFAULT"

  # contactPhoneMobileURL: "#"
  # contactPhoneMobileText: "DEFAULT"
  
  # contactEmailURL: "#"
  # contactEmailText: "DEFAULT"
 
  # contactAddressURL: "#"
  # contactAddressText1: "DEFAULT"
  # contactAddressText2: ""
  # contactAddressText3: ""
  
  # contactHelpURL: "#"
  # contactHelpText: "DEFAULT"
 
  # contactFacebookURL: "#"
  # contactFacebookText: "DEFAULT"

  # contactHoursEnabled: true
  # hoursRange:
  # - day: "Mon"
  #   open: "10am"
  #   close: "7pm"
  # - day: "Tue"
  #   open: "10am"
  #   close: "7pm"

  #solid icons
  contactEmailIcon: "icons/bootstrap/envelope.svg"
  contactPhoneMobileIcon: "icons/bootstrap/phone.svg"
  contactPhoneIcon: "icons/bootstrap/telephone.svg"
  contactAddressIcon: "icons/bootstrap/geo-alt.svg"
  contactHelpIcon: "icons/bootstrap/exclamation-triangle.svg"
  contactFacebookIcon: "icons/awesome/brands/facebook-f.svg"
  contactHoursIcon: "icons/bootstrap/clock.svg"


  ##########################
  # MOBILE FOOTER          #
  ##########################
  footerPhoneURL: "#"
  footerPhoneText: "DEFAULT"
  footerPhoneIcon: "icons/bootstrap/telephone.svg"


  #####################
  # c-social-links    #
  #####################

  # socialTwitterURL:
  # socialFacebookURL:
  # socialLinkedInURL:
  # socialInstagramURL: 
  # socialGoogleBizURL:
  
  socialTwitterIcon: "icons/simple/twitter.svg"
  socialFacebookIcon: "icons/awesome/brands/facebook-f.svg"
  socialsocialLinkedInIcon: "icons/simple/linkedin.svg"
  socialInstagramIcon: "icons/simple/instagram.svg"
  socialGoogleBizIcon: "icons/simple/google.svg"



  ##PHOTO CONFIG OLD
  landscapePhotoWidths: 
  - 1000
  - 800
  - 700
  - 600
  - 500
  - 400
  - 300
  portraitPhotoWidths: 
  - 800
  - 700
  - 600
  - 500
  - 400
  - 300
  - 200
  smallPhotoWidths:
  - 300
  - 200 
  - 100
  - 76
  - 50

  #SRCSET CONFIG
  photoWidthFull:
  - 535
  - 696
  - 936
  - 1140
  - 1296

  photoWidthCols:
  - 178
  - 279
  - 372
  - 468
  - 558
  - 648


  photoWidthThumb:
  - 32
  - 72
  - 96
  - 166
  - 196



  
  
  

  


